In [6]:


import pandas as pd

# Загрузка данных
df = pd.read_csv('denoising_results_for_ten_pics.csv')

# Функция для нахождения лучших результатов по PSNR и SSIM для каждой картинки и типа шума
def find_best_results(df):
    results = []
    images = df['image'].unique()
    noise_types = df['noise_type'].unique()

    for image in images:
        for noise_type in noise_types:
            subset = df[(df['image'] == image) & (df['noise_type'] == noise_type)]

            # Лучший PSNR
            best_psnr = subset.loc[subset['psnr'].idxmax()]
            results.append({
                'image': image,
                'noise_type': noise_type,
                'metric': 'PSNR',
                'denoising_method': best_psnr['denoising_method'],
                'strength': best_psnr['strength'],
                'mu': best_psnr['mu'],
                'value': best_psnr['psnr'],
                'ssim': best_psnr['ssim'],
                'output_path': best_psnr['output_path']
            })

            # Лучший SSIM
            best_ssim = subset.loc[subset['ssim'].idxmax()]
            results.append({
                'image': image,
                'noise_type': noise_type,
                'metric': 'SSIM',
                'denoising_method': best_ssim['denoising_method'],
                'strength': best_ssim['strength'],
                'mu': best_ssim['mu'],
                'value': best_ssim['ssim'],
                'psnr': best_ssim['psnr'],
                'output_path': best_ssim['output_path']
            })
    results = pd.DataFrame(results)
    return results

# Получаем лучшие результаты
best_results = find_best_results(df)

# Выводим результаты
best_results[['image', 'noise_type', 'metric', 'denoising_method', 'strength', 'mu', 'value', 'ssim', 'psnr']]

,image,noise_type,metric,denoising_method,strength,mu,value,ssim,psnr
0,airplaneU2.bmp,salt_pepper,PSNR,Moreau-Yosida,1.0,0.010,32.512536,0.051922,NaN
1,airplaneU2.bmp,salt_pepper,SSIM,Moreau-Yosida,0.1,0.001,0.063233,NaN,31.356267
2,airplaneU2.bmp,gaussian,PSNR,TV,0.1,0.001,33.373568,0.073139,NaN
3,airplaneU2.bmp,gaussian,SSIM,Moreau-Yosida,0.6,0.006,0.305333,NaN,32.717407
4,cablecar.bmp,salt_pepper,PSNR,Moreau-Yosida,0.9,0.009,39.175148,0.332090,NaN
5,cablecar.bmp,salt_pepper,SSIM,Moreau-Yosida,0.9,0.009,0.332090,NaN,39.175148
6,cablecar.bmp,gaussian,PSNR,Moreau-Yosida,0.5,0.005,32.700053,0.595684,NaN
7,cablecar.bmp,gaussian,SSIM,Moreau-Yosida,0.5,0.005,0.595684,NaN,32.700053
8,fruits.bmp,salt_pepper,PSNR,Moreau-Yosida,0.6,0.006,38.865310,0.245819,NaN
9,fruits.bmp,salt_pepper,SSIM,TV,0.1,0.001,0.247139,NaN,31.246946
10,fruits.bmp,gaussian,PSNR,Moreau-Yosida,0.5,0.005,33.691700,0.601305,NaN
11,fruits.bmp,gaussian,SSIM,Moreau-Yosida,0.2,0.002,0.602130,NaN,33.525404
12,goldhill.bmp,salt_pepper,PSNR,TV,0.1,0.001,30.114407,0.250774,NaN
13,goldhill.bmp,salt_pepper,SSIM,TV,0.1,0.001,0.250774,NaN,30.114407
14,goldhill.bmp,gaussian,PSNR,Moreau-Yosida,0.2,0.002,32.106857,0.575637,NaN
15,goldhill.bmp,gaussian,SSIM,Moreau-Yosida,0.2,0.002,0.575637,NaN,32.106857
16,Malamute.bmp,salt_pepper,PSNR,Moreau-Yosida,0.2,0.002,37.938680,0.360045,NaN
17,Malamute.bmp,salt_pepper,SSIM,Moreau-Yosida,0.2,0.002,0.360045,NaN,37.938680
18,Malamute.bmp,gaussian,PSNR,TV,0.1,0.001,30.289746,0.384895,NaN
19,Malamute.bmp,gaussian,SSIM,TV,0.1,0.001,0.384895,NaN,30.289746
20,pens.bmp,salt_pepper,PSNR,Moreau-Yosida,0.2,0.002,37.680585,0.332407,NaN
21,pens.bmp,salt_pepper,SSIM,TV,0.1,0.001,0.382586,NaN,30.105622
22,pens.bmp,gaussian,PSNR,TV,0.1,0.001,31.140397,0.466882,NaN
23,pens.bmp,gaussian,SSIM,TV,0.1,0.001,0.466882,NaN,31.140397
24,flowers.ppm,salt_pepper,PSNR,TV,0.1,0.001,29.924477,0.334648,NaN
25,flowers.ppm,salt_pepper,SSIM,TV,0.1,0.001,0.334648,NaN,29.924477
26,flowers.ppm,gaussian,PSNR,TV,0.1,0.001,30.392424,0.388734,NaN
27,flowers.ppm,gaussian,SSIM,TV,0.1,0.001,0.388734,NaN,30.392424
28,soccer.ppm,salt_pepper,PSNR,TV,0.1,0.001,29.380513,0.371820,NaN
29,soccer.ppm,salt_pepper,SSIM,TV,0.1,0.001,0.371820,NaN,29.380513
30,soccer.ppm,gaussian,PSNR,TV,0.1,0.001,29.677620,0.417276,NaN
31,soccer.ppm,gaussian,SSIM,TV,0.1,0.001,0.417276,NaN,29.677620
32,yacht.ppm,salt_pepper,PSNR,Moreau-Yosida,0.5,0.005,38.387163,0.345255,NaN
33,yacht.ppm,salt_pepper,SSIM,Moreau-Yosida,0.5,0.005,0.345255,NaN,38.387163
34,yacht.ppm,gaussian,PSNR,Moreau-Yosida,0.3,0.003,32.576413,0.635362,NaN
35,yacht.ppm,gaussian,SSIM,Moreau-Yosida,0.3,0.003,0.635362,NaN,32.576413
36,lighthouse.pgm,salt_pepper,PSNR,TV,0.1,0.001,29.779664,0.231670,NaN
37,lighthouse.pgm,salt_pepper,SSIM,TV,0.1,0.001,0.231670,NaN,29.779664
38,lighthouse.pgm,gaussian,PSNR,Moreau-Yosida,0.1,0.001,30.850749,0.554585,NaN
39,lighthouse.pgm,gaussian,SSIM,Moreau-Yosida,0.1,0.001,0.554585,NaN,30.850749

In [10]:

SSIM_df = best_results[best_results['metric'] == 'SSIM']
SSIM_df

,image,noise_type,metric,denoising_method,strength,mu,value,ssim,output_path,psnr
1,airplaneU2.bmp,salt_pepper,SSIM,Moreau-Yosida,0.1,0.001,0.063233,NaN,Testing2\airplaneU2_salt_pepper_s0.1_m0.001_Mo...,31.356267
3,airplaneU2.bmp,gaussian,SSIM,Moreau-Yosida,0.6,0.006,0.305333,NaN,Testing2\airplaneU2_gaussian_s0.6_m0.006_Morea...,32.717407
5,cablecar.bmp,salt_pepper,SSIM,Moreau-Yosida,0.9,0.009,0.332090,NaN,Testing2\cablecar_salt_pepper_s0.9_m0.009_More...,39.175148
7,cablecar.bmp,gaussian,SSIM,Moreau-Yosida,0.5,0.005,0.595684,NaN,Testing2\cablecar_gaussian_s0.5_m0.005_MoreauY...,32.700053
9,fruits.bmp,salt_pepper,SSIM,TV,0.1,0.001,0.247139,NaN,Testing2\fruits_salt_pepper_s0.1_m0.001_TV.png,31.246946
11,fruits.bmp,gaussian,SSIM,Moreau-Yosida,0.2,0.002,0.602130,NaN,Testing2\fruits_gaussian_s0.2_m0.002_MoreauYos...,33.525404
13,goldhill.bmp,salt_pepper,SSIM,TV,0.1,0.001,0.250774,NaN,Testing2\goldhill_salt_pepper_s0.1_m0.001_TV.png,30.114407
15,goldhill.bmp,gaussian,SSIM,Moreau-Yosida,0.2,0.002,0.575637,NaN,Testing2\goldhill_gaussian_s0.2_m0.002_MoreauY...,32.106857
17,Malamute.bmp,salt_pepper,SSIM,Moreau-Yosida,0.2,0.002,0.360045,NaN,Testing2\Malamute_salt_pepper_s0.2_m0.002_More...,37.938680
19,Malamute.bmp,gaussian,SSIM,TV,0.1,0.001,0.384895,NaN,Testing2\Malamute_gaussian_s0.1_m0.001_TV.png,30.289746
21,pens.bmp,salt_pepper,SSIM,TV,0.1,0.001,0.382586,NaN,Testing2\pens_salt_pepper_s0.1_m0.001_TV.png,30.105622
23,pens.bmp,gaussian,SSIM,TV,0.1,0.001,0.466882,NaN,Testing2\pens_gaussian_s0.1_m0.001_TV.png,31.140397
25,flowers.ppm,salt_pepper,SSIM,TV,0.1,0.001,0.334648,NaN,Testing2\flowers_salt_pepper_s0.1_m0.001_TV.png,29.924477
27,flowers.ppm,gaussian,SSIM,TV,0.1,0.001,0.388734,NaN,Testing2\flowers_gaussian_s0.1_m0.001_TV.png,30.392424
29,soccer.ppm,salt_pepper,SSIM,TV,0.1,0.001,0.371820,NaN,Testing2\soccer_salt_pepper_s0.1_m0.001_TV.png,29.380513
31,soccer.ppm,gaussian,SSIM,TV,0.1,0.001,0.417276,NaN,Testing2\soccer_gaussian_s0.1_m0.001_TV.png,29.677620
33,yacht.ppm,salt_pepper,SSIM,Moreau-Yosida,0.5,0.005,0.345255,NaN,Testing2\yacht_salt_pepper_s0.5_m0.005_MoreauY...,38.387163
35,yacht.ppm,gaussian,SSIM,Moreau-Yosida,0.3,0.003,0.635362,NaN,Testing2\yacht_gaussian_s0.3_m0.003_MoreauYosi...,32.576413
37,lighthouse.pgm,salt_pepper,SSIM,TV,0.1,0.001,0.231670,NaN,Testing2\lighthouse_salt_pepper_s0.1_m0.001_TV...,29.779664
39,lighthouse.pgm,gaussian,SSIM,Moreau-Yosida,0.1,0.001,0.554585,NaN,Testing2\lighthouse_gaussian_s0.1_m0.001_Morea...,30.850749

In [11]:
PSNR_df = best_results[best_results['metric'] == 'PSNR']
PSNR_df

,image,noise_type,metric,denoising_method,strength,mu,value,ssim,output_path,psnr
0,airplaneU2.bmp,salt_pepper,PSNR,Moreau-Yosida,1.0,0.010,32.512536,0.051922,Testing2\airplaneU2_salt_pepper_s1.0_m0.010_Mo...,NaN
2,airplaneU2.bmp,gaussian,PSNR,TV,0.1,0.001,33.373568,0.073139,Testing2\airplaneU2_gaussian_s0.1_m0.001_TV.png,NaN
4,cablecar.bmp,salt_pepper,PSNR,Moreau-Yosida,0.9,0.009,39.175148,0.332090,Testing2\cablecar_salt_pepper_s0.9_m0.009_More...,NaN
6,cablecar.bmp,gaussian,PSNR,Moreau-Yosida,0.5,0.005,32.700053,0.595684,Testing2\cablecar_gaussian_s0.5_m0.005_MoreauY...,NaN
8,fruits.bmp,salt_pepper,PSNR,Moreau-Yosida,0.6,0.006,38.865310,0.245819,Testing2\fruits_salt_pepper_s0.6_m0.006_Moreau...,NaN
10,fruits.bmp,gaussian,PSNR,Moreau-Yosida,0.5,0.005,33.691700,0.601305,Testing2\fruits_gaussian_s0.5_m0.005_MoreauYos...,NaN
12,goldhill.bmp,salt_pepper,PSNR,TV,0.1,0.001,30.114407,0.250774,Testing2\goldhill_salt_pepper_s0.1_m0.001_TV.png,NaN
14,goldhill.bmp,gaussian,PSNR,Moreau-Yosida,0.2,0.002,32.106857,0.575637,Testing2\goldhill_gaussian_s0.2_m0.002_MoreauY...,NaN
16,Malamute.bmp,salt_pepper,PSNR,Moreau-Yosida,0.2,0.002,37.938680,0.360045,Testing2\Malamute_salt_pepper_s0.2_m0.002_More...,NaN
18,Malamute.bmp,gaussian,PSNR,TV,0.1,0.001,30.289746,0.384895,Testing2\Malamute_gaussian_s0.1_m0.001_TV.png,NaN
20,pens.bmp,salt_pepper,PSNR,Moreau-Yosida,0.2,0.002,37.680585,0.332407,Testing2\pens_salt_pepper_s0.2_m0.002_MoreauYo...,NaN
22,pens.bmp,gaussian,PSNR,TV,0.1,0.001,31.140397,0.466882,Testing2\pens_gaussian_s0.1_m0.001_TV.png,NaN
24,flowers.ppm,salt_pepper,PSNR,TV,0.1,0.001,29.924477,0.334648,Testing2\flowers_salt_pepper_s0.1_m0.001_TV.png,NaN
26,flowers.ppm,gaussian,PSNR,TV,0.1,0.001,30.392424,0.388734,Testing2\flowers_gaussian_s0.1_m0.001_TV.png,NaN
28,soccer.ppm,salt_pepper,PSNR,TV,0.1,0.001,29.380513,0.371820,Testing2\soccer_salt_pepper_s0.1_m0.001_TV.png,NaN
30,soccer.ppm,gaussian,PSNR,TV,0.1,0.001,29.677620,0.417276,Testing2\soccer_gaussian_s0.1_m0.001_TV.png,NaN
32,yacht.ppm,salt_pepper,PSNR,Moreau-Yosida,0.5,0.005,38.387163,0.345255,Testing2\yacht_salt_pepper_s0.5_m0.005_MoreauY...,NaN
34,yacht.ppm,gaussian,PSNR,Moreau-Yosida,0.3,0.003,32.576413,0.635362,Testing2\yacht_gaussian_s0.3_m0.003_MoreauYosi...,NaN
36,lighthouse.pgm,salt_pepper,PSNR,TV,0.1,0.001,29.779664,0.231670,Testing2\lighthouse_salt_pepper_s0.1_m0.001_TV...,NaN
38,lighthouse.pgm,gaussian,PSNR,Moreau-Yosida,0.1,0.001,30.850749,0.554585,Testing2\lighthouse_gaussian_s0.1_m0.001_Morea...,NaN